title:             FthZKrtn's Blog
email:             fatih@karatana.com
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           "/"
url:               "https://fthzkrtn.github.io"

# Social Profiles
twitter_username:  fthzkrtn
github_username:   fthzkrtn
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
